# Generated by Django 3.2.8 on 2021-10-25 05:51

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BlogCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256, unique=True, verbose_name='Title: ')),
            ],
            options={
                'verbose_name': 'Blog Category',
                'verbose_name_plural': 'Blog Categories.',
            },
        ),
        migrations.CreateModel(
            name='PodcastCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256, unique=True, verbose_name='Title :')),
            ],
            options={
                'verbose_name': 'Podcast Category',
                'verbose_name_plural': 'Podcast Categories',
            },
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256, unique=True, verbose_name='Title :')),
                ('description', models.TextField(verbose_name='Description :')),
                ('icon', models.CharField(max_length=30, verbose_name='Icon name :')),
            ],
            options={
                'verbose_name': 'Skill',
                'verbose_name_plural': 'Skills',
            },
        ),
        migrations.CreateModel(
            name='VideocastCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256, unique=True, verbose_name='Title :')),
            ],
            options={
                'verbose_name': 'Video Cast Category',
                'verbose_name_plural': 'Video Cast Categories',
            },
        ),
        migrations.CreateModel(
            name='Videocast',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256, unique=True, verbose_name='Title :')),
                ('slug', models.SlugField(max_length=256, unique=True, verbose_name='Slug :')),
                ('thumbnail', models.ImageField(upload_to='content/video/thumbnail/', verbose_name='Thumbnail :')),
                ('publish', models.BooleanField(default=True, help_text='Will this video be published?', verbose_name='Publish :')),
                ('video', models.CharField(max_length=256, verbose_name='Video link :')),
                ('content', ckeditor_uploader.fields.RichTextUploadingField()),
                ('category', models.ManyToManyField(to='core.VideocastCategory')),
            ],
            options={
                'verbose_name': 'Video Cast',
                'verbose_name_plural': 'Video Casts',
            },
        ),
        migrations.CreateModel(
            name='Podcast',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256, unique=True, verbose_name='Title :')),
                ('slug', models.SlugField(max_length=256, unique=True, verbose_name='Slug :')),
                ('thumbnail', models.ImageField(upload_to='content/podcast/thumbnail/', verbose_name='Thumbnail :')),
                ('publish', models.BooleanField(default=True, help_text='Will this audio be published?', verbose_name='Publish :')),
                ('audio', models.FileField(upload_to='content/podcast/audio/', verbose_name='Audio :')),
                ('content', ckeditor_uploader.fields.RichTextUploadingField()),
                ('category', models.ManyToManyField(to='core.PodcastCategory')),
            ],
            options={
                'verbose_name': 'Podcast',
                'verbose_name_plural': 'Podcasts',
            },
        ),
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256, unique=True, verbose_name='Title :')),
                ('slug', models.SlugField(max_length=256, unique=True, verbose_name='Slug :')),
                ('thumbnail', models.ImageField(upload_to='content/blog/thumbnail/', verbose_name='Thumbnail :')),
                ('publish', models.BooleanField(default=True, help_text='Will this post be published?', verbose_name='Publish :')),
                ('content', ckeditor_uploader.fields.RichTextUploadingField()),
                ('category', models.ManyToManyField(to='core.BlogCategory')),
            ],
            options={
                'verbose_name': 'Blog',
                'verbose_name_plural': 'Blogs',
            },
        ),
    ]
