"""
Django settings for blog project.

Generated by 'django-admin startproject' using Django 3.2.5.

For more information on this file, see
https://docs.djangoproject.com/en/3.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.2/ref/settings/
"""
import os
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
def sercret_key():
    from django.core.management.utils import get_random_secret_key as sec
    return sec()
    
SECRET_KEY = sercret_key()
# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['127.0.0.1','shaishguni-blog.herokuapp.com']


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'constance',
    'constance.backends.database',
    'ckeditor',
    'ckeditor_uploader',
    'content.apps.ContentConfig'
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
     'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    
]

ROOT_URLCONF = 'blog.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR,"templates")],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'content.context_processors.show_system_content',
            ],
        },
    },
]

WSGI_APPLICATION = 'blog.wsgi.application'


# Database
# https://docs.djangoproject.com/en/3.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': os.path.join(BASE_DIR , 'db.sqlite3'),
    }
}


# Password validation
# https://docs.djangoproject.com/en/3.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/3.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Asia/Kathmandu'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.0/howto/static-files/
STATIC_URL = '/static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'static')
STATICFILES_DIRS = [
    os.path.join(BASE_DIR, "templates/static"),
]

# Media files
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')
MEDIA_URL = '/media/'

# CKEditor
CKEDITOR_UPLOAD_PATH = "uploads/"

CKEDITOR_CONFIGS = {
    'default': {
        'toolbar': 'full',
    },
}

# CONSTANCE Settings
CONSTANCE_BACKEND = 'constance.backends.database.DatabaseBackend'

CONSTANCE_IGNORE_ADMIN_VERSION_CHECK = True

CACHES = {
    'default': {
        'BACKEND': 'django.core.cache.backends.memcached.MemcachedCache',
        'LOCATION': '127.0.0.1:11211',
    }
}
CONSTANCE_DATABASE_CACHE_BACKEND = 'default'

CONSTANCE_ADDITIONAL_FIELDS = {
    'yes_no_select': ['django.forms.fields.ChoiceField', {
        'widget': 'django.forms.Select',
        'choices': (
            ("yes", ('Yes')),
            ("no", ('No'))
        )
    }],
    'image_field': ['django.forms.ImageField', {}]
}

CONSTANCE_CONFIG = {
    'SITE_TITLE': ('My Blog', ('Title of this site!'), str),
    'SITE_DESCRIPTION': ('Blog Description', ('Description of this site!'), str),
    'SITE_FAVICON': ('default_favicon.png', ('Favicon of this site!'), 'image_field'),

    'GET_IN_TOUCH_ACTIVE': ('yes', ('"Get in touch" section is active?'), 'yes_no_select'),
    'GET_IN_TOUCH_INFO': ('Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.', ('"Get in touch" information text'), str),
    'GET_IN_TOUCH_EMAIL_ADDRESS': ('information@untitled.tld', ('"Get in touch" email address'), str),
    'GET_IN_TOUCH_PHONE': ('(000) 000-0000', ('"Get in touch" phone number'), str),
    'GET_IN_TOUCH_ADDRESS': ('1234 Somewhere Road #8254<br />Nashville, TN 00000-0000', ('"Get in touch" address'), str),

    'SOCIAL_NETWORKS_FACEBOOK_URL': ('#', ('Social Networks - Facebook'), str),
    'SOCIAL_NETWORKS_TWITTER_URL': ('#', ('Social Networks - Twitter'), str),
    'SOCIAL_NETWORKS_INSTAGRAM_URL': ('#', ('Social Networks - Instagram'), str),
    'SOCIAL_NETWORKS_GITHUB_URL': ('#', ('Social Networks - Github'), str),
}

CONSTANCE_CONFIG_FIELDSETS = {
    'General Options': (
        'SITE_TITLE',
        'SITE_DESCRIPTION',
        'SITE_FAVICON',
    ),
    '"Get in touch" Options': (
        'GET_IN_TOUCH_ACTIVE',
        'GET_IN_TOUCH_INFO',
        'GET_IN_TOUCH_EMAIL_ADDRESS',
        'GET_IN_TOUCH_PHONE',
        'GET_IN_TOUCH_ADDRESS',
    ),
    '"Social Networks" Options': (
        'SOCIAL_NETWORKS_FACEBOOK_URL',
        'SOCIAL_NETWORKS_TWITTER_URL',
        'SOCIAL_NETWORKS_INSTAGRAM_URL',
        'SOCIAL_NETWORKS_GITHUB_URL',
    ),
}
# CONSTANCE Settings

# Auth Settings
LOGIN_REDIRECT_URL = 'content:index'
LOGIN_URL = 'login'
LOGOUT_REDIRECT_URL = 'content:index'

# Default primary key field type
# https://docs.djangoproject.com/en/3.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_PORT = 587
EMAIL_USE_TLS = True
EMAIL_HOST_USER = "youremail@gmail.com" 
EMAIL_HOST_PASSWORD = "yourpassword"


# some works for whitenoise
STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'